INSERT INTO `questions` (`id`, `ques`) VALUES
	(1, 'Saya berminat dengan kursus ini.<br/> <i>\nI am interested in this course.</i>\n'),
	(2, 'Saya sentiasa hadir ke sesi syarahan/tutorial/makmal/studio/kerja lapangan untuk kursus ini. <br/><i>\nI am always present during all lecture/tutorial/studio/fieldwork sessions for this course.</i>\n'),
	(3, 'Saya sentiasa bersedia untuk setiap sesi syarahan/tutorial/makmal/studio/kerja lapangan untuk kursus ini.<br/><i>\nI am always prepared for every lecture/tutorial/laboratory/studio/fieldwork sessions for this course.</i>\n'),
	(4, 'Pensyarah memaklumkan perancangan pengajaran/skema kerja kepada pelajar.<br/><i>\nThe lecturer informs the students about the teaching plan/scheme of work for this course.</i>\n'),
	(5, 'Pensyarah menerangkan dengan jelas tentang hasil kursus dan pembelajaran kepada pelajar.<br/><i>\nThe lecturer provides a clear explanation about the course outcomes and the learning outcomes to the students.</i>\n'),
	(6, 'Pensyarah menerangkan cara penilaian kursus dengan jelas kepada pelajar.<br/><i>\nThe lecturer clearly explains to the students the assessment procedure for this course.</i>\n'),
	(7, 'Pensyarah mengendalikan sesi syarahan/tutorial/makmal/studio/klinikal/kerja lapangan yang ditangguhkan.<br/><i>\nThe lecturer conducts lecture/tutorial/laboratory/studio/clinical/fieldwork sessions based on the teaching plan for this course.</i>'),
	(8, 'Pensyarah memenuhi waktu pengajaran yang dijadualkan.<br/><i>\nThe lecturer observes the scheduled training hours for this course.</i>'),
	(9, 'Pensyarah menggantikan setiap sesi syarahan/tutorial/makmal/studio/klinikal/kerja lapangan yang ditangguhkan.<br/>\n(Sekiranya pensyarah tidak pernah menangguhkan kelas, sila abaikan soalan ini.)<br/><i>\nThe lecturer replaces every lecture/tutorial/laboratory/studio/clinical/field work sessions which has been postponed.<br/>\n(If lecturer never postpones lecture, do not answer this question.)</i>\n'),
	(10, 'Pensyarah mengambil berat tentang kehadiran pelajar. <br/><i>\nThe lecturer is concerned about the studentsâ€™ attendance.</i>'),
	(11, 'Pensyarah menggunakan Bahasa Inggeris sebagai bahasa pengantar semasa kuliah (jika berkaitan). <br/><i>\nThe lecturer uses English language during lectures (where applicable).</i>\n'),
	(12, 'Pensyarah sentiasa bersedia untuk setiap sesi pertemuan/pengajaran.<br/><i>\nThe lecturer is always prepared for every meeting/lecture.</i>'),
	(13, 'Pensyarah berusaha untuk membantu pelajar untuk memahami pelajaran.<br/><i>\nThe lecturer makes effort to help students understand the lessons.</i>'),
	(14, 'Pensyarah menggunakan/mencadangkan bahan pengajaran/pembelajaran/rujukan yang sesuai.<br/><i>\nThe lecturer uses/suggests suitable teaching aids/references.</i>'),
	(15, 'Pensyarah menggunakan kaedah penyampaian yang sesuai dan berkesan.<br/><i>\nThe lecturer uses effective and appropriate teaching techniques.</i>'),
	(16, 'Pensyarah menggalakkan pelajar bertanya soalan dan mengemukakan pendapat.<br/><i>\nThe lecturer encourages the students to ask questions and give opinions.</i>'),
	(17, 'Pensyarah bersedia memberi bimbingan akademik kepada pelajar.<br/><i>\nThe lecturer is prepared to provide academic guidance to students.</i>'),
	(18, 'Pensyarah memberi ujian/penilaian/tugasan yang sesuai dengan hasil pembelajaran dan hasil kusus.<br/>\nThe lecturer gives tests/evaluation/assignments in line with the learning and course outcomes.'),
	(19, 'Pensyarah memaklumkan setiap hasil penilaian kepada pelajar. <br/><i>\nThe lecturer informs every assessment results to the students.</i>\n'),
	(20, 'Pensyarah berpakaian kemas dan sopan.<br/><i>\nThe lecturer is appropriately attired.</i>\n'),
	(21, 'Pensyarah membincangkan isu-isu yang relevan dengan bidang semasa sesi pertemuan rasmi.<br/><i>\nThe lecturer discusses relevant issues pertaining to the course during lectures.</i>\n'),
	(22, 'Pensyarah mudah dihubungi untuk perbincangan.<br/><i>\nThe lecturer is easily contactable for discussions. </i>\n'),
	(23, 'Secara keseluruhannya, saya berpuas hati dengan pengajaran pensyarah ini.<br/><i>\nIn general, I am satisfied with the lecturerâ€™s teaching.</i>'),
	(24, 'Kelengkapan ruang kondusif untuk pembelajaran dan pengajaran.<br/><i>\nThe space is conducive for teaching and learning.</i>\n'),
	(25, 'Kelengkapan dan peralatan pengajaran bagi kursus ini mencukupi dan berfungsi.<br/><i>\nThe teaching and learning equipments are adequate and functioning.</i>\n'),
	(26, 'Nyatakan apa yang anda suka tentang kursus ini.<br/><i>\nState what you like about this course.</i>\n'),
	(27, 'Cadangkan aspek penambahbaikan untuk kursus ini.<br/><i>\nSuggest improvements to aspects of the course.</i>');